services:
  db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    container_name: redis_queue
    restart: always
    ports:
      - "6379:6379"

  redis-insight:
    image: redis/redisinsight:latest
    container_name: redis_ui
    ports:
      - "8001:8001"
