spring.application.name=matchworker

# ✅ Redis
# spring.data.redis.host=localhost
# spring.data.redis.port=6379

spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}


# ✅ Postgres
# spring.datasource.url=jdbc:postgresql://localhost:5432/mydatabase
# spring.datasource.username=myuser
# spring.datasource.password=mypassword

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# SSL for Neon
spring.datasource.hikari.data-source-properties.ssl=true
spring.datasource.hikari.data-source-properties.sslmode=require


# ✅ JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

groq.api.key=${GROQ_API_KEY}

server.port=${PORT:8080}

